global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nodejs-server'
    static_configs:
      - targets: ['node_app:5000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'event-detector'
    static_configs:
      - targets: ['event_detector:8000']
      
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
